include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - test/integration/error_fixture/**

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules:
    prefer-publish-to-none: false
    # TODO: Support analyzer same way as json_serializable https://github.com/google/json_serializable.dart/pull/1333
    prefer-caret-version-syntax: false
  rules:
    avoid-unnecessary-call: false # the Expression API uses a lot of `.call` which is clearer
    avoid-top-level-members-in-tests:
      exclude:
        - test/integration/fixture/**
    avoid-commented-out-code: false # code examples in comments
    prefer-single-declaration-per-file:
      exclude:
        - test/integration/fixture/**
    prefer-named-parameters: false # TODO: release new major version (breaking change)
    prefer-boolean-prefixes: false # TODO: release new major version (breaking change)


    # TODO: release new major version (breaking change) - uncomment lines below
    # prefer-boolean-prefixes:
    #   exclude:
    #     - test/integration/fixture/**
    #   prefixes: ['include' , 'use', 'are', 'assign', 'with', 'will', 'maybe']
